stages:
  - bundle
  - release

variables:
  ADDON_INIT: "__init__.py"
  ZIP_NAME: "blendertools.zip"

bundle_addon:
  stage: bundle
  image: python:3.11
  script:
    - |
      VERSION=$(python3 -c "
      import ast
      with open('$ADDON_INIT') as f:
          tree = ast.parse(f.read())
      bl_info = next(n for n in tree.body if isinstance(n, ast.Assign) and n.targets[0].id == 'bl_info').value
      ver = next((kw.value for kw in bl_info.keys if kw.s == 'version'), None)
      if ver:
          print('.'.join(str(n.value) for n in ver.elts))
      ")
      echo "VERSION=$VERSION" >> release.env
    - |
      PRERELEASE=$(python3 -c "
      import ast
      with open('$ADDON_INIT') as f:
          tree = ast.parse(f.read())
      bl_info = next(n for n in tree.body if isinstance(n, ast.Assign) and n.targets[0].id == 'bl_info').value
      warn = next((kw.value.s for kw in bl_info.keys if kw.s == 'warning'), '')
      print('true' if warn == 'This Addon is still in Development!' else 'false')
      ")
      echo "PRERELEASE=$PRERELEASE" >> release.env
    - zip -r "$ZIP_NAME" . -x "*.git*" "*.venv*" "__pycache__/*" "*.mypy_cache*" "*.vscode*" ".mypy_cache/*"
  artifacts:
    paths:
      - $ZIP_NAME
      - release.env
    reports:
      dotenv: release.env

release:
  stage: release
  image: python:3.11
  script:
    - |
      if [ "$PRERELEASE" = "true" ]; then
        TITLE="Blender Tools v$VERSION (Pre-Release)"
        DESC="This is a pre-release version of Blender Tools.\n\nVersion: $VERSION"
      else
        TITLE="Blender Tools v$VERSION"
        DESC="Stable release of Blender Tools.\n\nVersion: $VERSION"
      fi
      echo "RELEASE_TITLE=$TITLE" >> release.env
      echo -e "RELEASE_DESC=$DESC" >> release.env
  artifacts:
    reports:
      dotenv: release.env

  release:
    tag_name: "v$VERSION"
    name: "$RELEASE_TITLE"
    description: "$RELEASE_DESC"
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: "Download .zip"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/$ZIP_NAME"
